import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
);

const properties = [
  {
    id: "prop-001",
    title: "Bandra Sea-View Estate",
    description:
      "Perched above the iconic Bandstand Promenade with sweeping Arabian Sea views, this stunning contemporary home blends natural stone, exposed steel, and floor-to-ceiling glass. The open-plan living area flows seamlessly to an expansive deck with an infinity pool overlooking the sea. The chef's kitchen features top-of-the-line appliances, quartzite counters, and a butler's pantry.",
    status: "For Sale",
    type: "House",
    price: 75000000,
    address: "14, Bandstand Promenade, Bandra West",
    city: "Mumbai",
    state: "MH",
    zip: "400050",
    bedrooms: 5,
    bathrooms: 4,
    sqft: 4800,
    garage: 3,
    year_built: 2021,
    floors: 2,
    features: ["Infinity Pool", "Home Theater", "Smart Home", "Wine Cellar", "Guest Suite", "Solar Panels"],
    images: [
      { url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80", alt: "Exterior view" },
      { url: "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&q=80", alt: "Living room" },
      { url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80", alt: "Kitchen" },
    ],
    is_featured: true,
    agent_id: "agent-001",
    listed_at: "2024-11-15",
  },
  {
    id: "prop-002",
    title: "BKC Luxury Penthouse",
    description:
      "This exceptional penthouse occupies the entire top floor of one of Mumbai's most coveted addresses in Bandra Kurla Complex. Sweeping views of the city skyline greet you from every room. Features include a private rooftop terrace with a hot tub, custom Italian cabinetry, heated marble floors, and a private elevator foyer.",
    status: "For Sale",
    type: "Apartment",
    price: 68000000,
    address: "801, Platinum Tower, Bandra Kurla Complex",
    city: "Mumbai",
    state: "MH",
    zip: "400051",
    bedrooms: 4,
    bathrooms: 3,
    sqft: 3600,
    garage: 2,
    year_built: 2019,
    floors: 1,
    features: ["Private Rooftop", "Hot Tub", "Private Elevator", "Concierge", "Heated Floors", "City Views"],
    images: [
      { url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80", alt: "Penthouse exterior" },
      { url: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800&q=80", alt: "Living area" },
      { url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80", alt: "Kitchen" },
    ],
    is_featured: true,
    agent_id: "agent-002",
    listed_at: "2024-10-22",
  },
  {
    id: "prop-003",
    title: "Indiranagar Modern Villa",
    description:
      "A beautifully crafted modern residence in Bangalore's sought-after Indiranagar neighbourhood. This home features an open-concept layout with polished concrete floors, custom built-ins, and a stunning glass-enclosed staircase. The rooftop deck offers panoramic city views.",
    status: "For Sale",
    type: "House",
    price: 32000000,
    address: "42, 12th Main Road, Indiranagar",
    city: "Bangalore",
    state: "KA",
    zip: "560038",
    bedrooms: 3,
    bathrooms: 2,
    sqft: 2400,
    garage: 1,
    year_built: 2020,
    floors: 3,
    features: ["Rooftop Deck", "EV Charging", "Smart Home", "Landscaped Garden", "Bike Storage"],
    images: [
      { url: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80", alt: "Exterior" },
      { url: "https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=800&q=80", alt: "Living room" },
      { url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80", alt: "Kitchen" },
    ],
    is_featured: false,
    agent_id: "agent-004",
    listed_at: "2024-12-03",
  },
  {
    id: "prop-004",
    title: "Lutyens Delhi Luxury Apartment",
    description:
      "Colonial elegance meets modern luxury in this stunning high-floor apartment on Prithviraj Road in Lutyens Delhi. Newly renovated with top-of-the-line finishes, the apartment retains its original architectural grandeur including high ceilings, herringbone oak floors, and a wood-burning fireplace.",
    status: "For Rent",
    type: "Apartment",
    price: 125000,
    address: "7B, Prithviraj Road, Lutyens Delhi",
    city: "New Delhi",
    state: "DL",
    zip: "110011",
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1800,
    garage: null,
    year_built: 1965,
    floors: 1,
    features: ["Garden Views", "24/7 Security", "Fireplace", "Laundry", "Storage Unit", "Gym"],
    images: [
      { url: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80", alt: "Building exterior" },
      { url: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800&q=80", alt: "Living room" },
      { url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80", alt: "Kitchen" },
    ],
    is_featured: true,
    agent_id: "agent-001",
    listed_at: "2025-01-10",
  },
  {
    id: "prop-005",
    title: "Koregaon Park Modern Condo",
    description:
      "A sleek, modern condo in Pune's vibrant Koregaon Park neighbourhood. This sunlit corner unit features an open kitchen with a waterfall island, spa bath with heated floors, and a private balcony overlooking tree-lined lanes.",
    status: "For Rent",
    type: "Apartment",
    price: 45000,
    address: "301, Ivy Residences, Lane 5, Koregaon Park",
    city: "Pune",
    state: "MH",
    zip: "411001",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1350,
    garage: 1,
    year_built: 2018,
    floors: 1,
    features: ["Balcony", "Rooftop Deck", "Gym", "Heated Floors", "In-unit Laundry"],
    images: [
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80", alt: "Building" },
      { url: "https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=800&q=80", alt: "Living room" },
      { url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80", alt: "Kitchen" },
    ],
    is_featured: false,
    agent_id: "agent-003",
    listed_at: "2025-01-20",
  },
  {
    id: "prop-006",
    title: "Hiranandani Lakeside Apartment",
    description:
      "Floor-to-ceiling windows showcase breathtaking Powai Lake and Mumbai skyline views from this luxury high-rise residence in Hiranandani Gardens. The unit boasts an open layout, Italian porcelain floors, a gourmet kitchen, and access to world-class amenities.",
    status: "For Rent",
    type: "Apartment",
    price: 85000,
    address: "1204, Skylark Tower, Hiranandani Gardens, Powai",
    city: "Mumbai",
    state: "MH",
    zip: "400076",
    bedrooms: 3,
    bathrooms: 3,
    sqft: 1950,
    garage: null,
    year_built: 2022,
    floors: 1,
    features: ["Lake Views", "Pool", "Spa", "Concierge", "Valet", "Pet Friendly"],
    images: [
      { url: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80", alt: "Building" },
      { url: "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&q=80", alt: "Living room" },
      { url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80", alt: "Kitchen" },
    ],
    is_featured: true,
    agent_id: "agent-003",
    listed_at: "2025-02-05",
  },
  {
    id: "prop-007",
    title: "Jubilee Hills Luxury Villa",
    description:
      "Set in the prestigious Jubilee Hills enclave of Hyderabad, this ultra-luxurious villa is the pinnacle of contemporary South Indian living. Custom designed by an award-winning architect, it features hand-crafted stone details, tropical landscaping, and a resort-worthy pool complex.",
    status: "For Sale",
    type: "Villa",
    price: 80000000,
    address: "8-2-293/82/A, Road No. 36, Jubilee Hills",
    city: "Hyderabad",
    state: "TS",
    zip: "500033",
    bedrooms: 6,
    bathrooms: 7,
    sqft: 8200,
    garage: 4,
    year_built: 2020,
    floors: 2,
    features: ["Resort Pool", "Outdoor Kitchen", "Tennis Court", "Guest House", "Home Theater", "Wine Room"],
    images: [
      { url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&q=80", alt: "Villa exterior" },
      { url: "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&q=80", alt: "Living area" },
      { url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80", alt: "Kitchen" },
    ],
    is_featured: true,
    agent_id: "agent-001",
    listed_at: "2024-09-15",
  },
  {
    id: "prop-008",
    title: "ECR Beachfront Villa",
    description:
      "Private paradise on Chennai's coveted East Coast Road. This magnificent beachfront villa sits on a rare double plot with 180 feet of direct sea access. The home's design emphasises indoor-outdoor living with retractable glass walls, a screened veranda, and tiered terraces leading to a private beach.",
    status: "For Sale",
    type: "Villa",
    price: 78000000,
    address: "142, East Coast Road, Thiruvanmiyur",
    city: "Chennai",
    state: "TN",
    zip: "600041",
    bedrooms: 7,
    bathrooms: 8,
    sqft: 10500,
    garage: 4,
    year_built: 2022,
    floors: 3,
    features: ["Private Beach", "Boat Dock", "Infinity Pool", "Guest Quarters", "Elevator", "Smart Home"],
    images: [
      { url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&q=80", alt: "Beachfront exterior" },
      { url: "https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=800&q=80", alt: "Living room" },
      { url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80", alt: "Kitchen" },
    ],
    is_featured: true,
    agent_id: "agent-003",
    listed_at: "2024-08-20",
  },
  {
    id: "prop-009",
    title: "Sector 18 Noida Condo",
    description:
      "A stylish urban condo in Noida's vibrant Sector 18, steps from the best restaurants, shopping, and entertainment. Features a sleek open floor plan, quartz counters, premium appliances, and a private balcony with city views.",
    status: "For Sale",
    type: "Apartment",
    price: 5500000,
    address: "A-504, The Residency, Sector 18",
    city: "Noida",
    state: "UP",
    zip: "201301",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1100,
    garage: null,
    year_built: 2021,
    floors: 1,
    features: ["City Views", "Pool", "Gym", "Dog Park", "Concierge"],
    images: [
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80", alt: "Building" },
      { url: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800&q=80", alt: "Living room" },
      { url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80", alt: "Kitchen" },
    ],
    is_featured: false,
    agent_id: "agent-004",
    listed_at: "2025-01-30",
  },
  {
    id: "prop-010",
    title: "DLF Cyber City Loft",
    description:
      "A dramatic industrial-chic corner loft in the heart of Gurgaon's DLF Cyber City district. Soaring 14-foot ceilings, exposed brick walls, and polished concrete floors create a distinctive urban backdrop. Oversized windows flood the space with natural light.",
    status: "For Sale",
    type: "Apartment",
    price: 12000000,
    address: "1201, Horizon Tower, DLF Phase 2",
    city: "Gurgaon",
    state: "HR",
    zip: "122002",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1450,
    garage: null,
    year_built: 2016,
    floors: 1,
    features: ["14-ft Ceilings", "Exposed Brick", "Rooftop Pool", "Coworking Space", "Bike Storage"],
    images: [
      { url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80", alt: "Loft exterior" },
      { url: "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&q=80", alt: "Living area" },
      { url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80", alt: "Kitchen" },
    ],
    is_featured: false,
    agent_id: "agent-002",
    listed_at: "2025-02-12",
  },
  {
    id: "prop-011",
    title: "Koramangala Studio",
    description:
      "A beautifully appointed studio in Bangalore's vibrant Koramangala neighbourhood. Thoughtfully designed to maximise every square foot, this light-filled studio features custom built-ins, a Murphy bed, in-unit washer/dryer, and a Juliet balcony.",
    status: "For Rent",
    type: "Studio",
    price: 18000,
    address: "5D, Silver Oak Apartments, 5th Block, Koramangala",
    city: "Bangalore",
    state: "KA",
    zip: "560034",
    bedrooms: 0,
    bathrooms: 1,
    sqft: 480,
    garage: null,
    year_built: 2019,
    floors: 1,
    features: ["Murphy Bed", "Built-ins", "Juliet Balcony", "In-unit Laundry", "Bike Room"],
    images: [
      { url: "https://images.unsplash.com/photo-1630699144867-37acec22cb3b?w=800&q=80", alt: "Studio" },
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80", alt: "Living area" },
      { url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80", alt: "Kitchen" },
    ],
    is_featured: false,
    agent_id: "agent-004",
    listed_at: "2025-02-20",
  },
  {
    id: "prop-012",
    title: "Connaught Place Commercial Complex",
    description:
      "A prime commercial investment opportunity in Delhi's iconic Connaught Place. This mixed-use building includes ground-floor retail with long-term tenants, four office suites on floors two and three, and a rooftop terrace with panoramic city views.",
    status: "For Sale",
    type: "Commercial",
    price: 55000000,
    address: "F-12, Connaught Place",
    city: "New Delhi",
    state: "DL",
    zip: "110001",
    bedrooms: 0,
    bathrooms: 6,
    sqft: 14000,
    garage: null,
    year_built: 2015,
    floors: 3,
    features: ["Ground Floor Retail", "Office Suites", "Rooftop Terrace", "Parking", "Fiber Internet"],
    images: [
      { url: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80", alt: "Building exterior" },
      { url: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80", alt: "Office interior" },
      { url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80", alt: "Retail space" },
    ],
    is_featured: false,
    agent_id: "agent-002",
    listed_at: "2024-12-10",
  },
];

console.log(`Seeding ${properties.length} properties into Supabase…\n`);

const { data, error } = await supabase
  .from("properties")
  .upsert(properties, { onConflict: "id" })
  .select("id, title");

if (error) {
  console.error("Seed failed:", error.message);
  process.exit(1);
}

for (const row of data) {
  console.log(`  ✓ ${row.id}  ${row.title}`);
}

console.log(`\nDone — ${data.length} rows upserted.`);

const { count } = await supabase
  .from("properties")
  .select("*", { count: "exact", head: true });

console.log(`Total rows in table: ${count}`);
